language: cpp
sudo: false

branches:
  only:
    - master

linux64_addons:
    addons: &linux64
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
        - gcc-5
        - libboost-dev
        - libboost-filesystem1.54-dev
        - libboost-program-options1.54-dev

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc
      addons: *linux64
      env: COMPILER_C=gcc-5 COMPILER_CXX=g++-5 COVERAGE=ON
    - os: linux
      compiler: clang
      addons: *linux64
      env: COMPILER_C=clang COMPILER_CXX=clang++ COVERAGE=OFF
    - os: osx
      compiler: clang
      env: COMPILER_C=clang COMPILER_CXX=clang++ COVERAGE=OFF
    - os: osx
      compiler: gcc
      env: COMPILER_C=gcc COMPILER_CXX=g++ COVERAGE=OFF

before_install:
  - pip install --user cpp-coveralls
  
script:
  - export CC=${COMPILER_C}
  - export CXX=${COMPILER_CXX}
  - ${CC} --version
  - ${CXX} --version
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build
  - cmake .. -DCOVERAGE=${COVERAGE}
  - make -j2
  - ctest -j2 --output-on-failure

after_success:
  - cd $TRAVIS_BUILD_DIR
  - |
    if [[ "${COVERAGE}" == "ON" ]]; then
        coveralls --gcov gcov-5 -e build/chemfiles -e build/chemfiles_build -e build/CHEMFILES-prefix -e build/CMakeFiles -e progs -E '.*external.*' --gcov-options '\-lp'
    fi
