version: "{build}"
os: Visual Studio 2017

branches:
  only:
    - master

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  matrix:
    - generator: Visual Studio 14 2017
      ARCH: x86
      BUILD_TYPE: Release
      SHARED: OFF
    - generator: Visual Studio 14 2017 Win64
      ARCH: x64
      BUILD_TYPE: Release
      SHARED: ON
    - generator: Visual Studio 14 2017 Win64
      ARCH: x64
      BUILD_TYPE: Release
      SHARED: OFF
    - generator: Visual Studio 14 2017
      ARCH: x86
      BUILD_TYPE: Release
      SHARED: ON

clone_depth: 10
clone_folder: c:\lemon

# Uncomment the following lines to enable remote desktop access to Appveyor
# after a failed build.
# init:
#   - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
# on_failure:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - cd C:\lemon
  - mkdir build
  - cd build
  - cmake .. -DLEMON_TEST_ASYNC=ON -DLEMON_LINK_SHARED=%SHARED% -DLEMON_BUILD_PYTHON=ON
  - cmake --build . --config %BUILD_TYPE% -- /v:q /m

test_script:
  - ctest --build-config %BUILD_TYPE% --timeout 300 --output-on-failure
