version: "{build}"
os: Visual Studio 2017

branches:
  only:
    - master

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  TWINE_USERNAME:
    secure: QHW0ZSR1Ljzd+51LcuQkvw==
  TWINE_PASSWORD:
    secure: KOUl0H5qkKF0r5gIMkenoftnnkSCIufpCiQAURaB8Zo=
  matrix:
    - generator: Visual Studio 15 2017 Win64
      ARCH: x64
      SHARED: ON
      make_wheel: false
    - generator: Visual Studio 15 2017
      ARCH: x86
      SHARED: OFF
      make_wheel: false
    - generator: Visual Studio 15 2017 Win64
      ARCH: x64
      SHARED: ON
      make_wheel: false
    - generator: Visual Studio 15 2017
      ARCH: x86
      SHARED: ON
      make_wheel: false
    - generator: Visual Studio 15 2017 Win64
      ARCH: x64
      make_wheel: true

clone_depth: 10
clone_folder: c:\lemon

build_script:
  - ps: >-
      if ($env:make_wheel -ne 'true')
      {
        cd c:\lemon
        New-Item build -ItemType Directory
        cd build

        if ($env:ARCH -eq 'x64')
        {
          Set-Item -Path Env:Path -Value ("C:\Python35-x64\;" + $Env:Path)
        }

        cmake .. -DLEMON_TEST_ASYNC=ON `
                 -DLEMON_LINK_SHARED="$env:SHARED" `
                 -DLEMON_BUILD_PYTHON=ON `
                 -Wno-dev `
                 -G $env:generator

        cmake --build . --config Release -- /v:m /m:2
      }

test_script:
  - ps: >-
      if ($env:make_wheel -ne 'true')
      {
        cd c:\lemon\build
        ctest --build-config Release --timeout 300 --output-on-failure
      } 

install:
  - ps: >-
      if ($env:make_wheel -eq 'true')
      {
        cd c:\lemon
        .\scripts\appveyor\build-wheels.ps1
      }

deploy_script:
  - ps: >-
      if ($env:appveyor_repo_tag -eq 'true' -and $env:make_wheel -eq 'true')
      {
        cd c:\lemon
        .\scripts\appveyor\upload-pypi.ps1
      }
