version: "{build}"
os: Visual Studio 2017

branches:
  only:
    - master

environment:
  BOOST_ROOT: C:\Libraries\boost_1_67_0
  TWINE_USERNAME:
    secure: QHW0ZSR1Ljzd+51LcuQkvw==
  matrix:
    - generator: Visual Studio 14 2017 Win64
      ARCH: x64
      make_wheel: true
    - generator: Visual Studio 14 2017
      ARCH: x86
      BUILD_TYPE: Release
      SHARED: OFF
      make_wheel: false
    - generator: Visual Studio 14 2017 Win64
      ARCH: x64
      BUILD_TYPE: Release
      SHARED: ON
      make_wheel: false
    - generator: Visual Studio 14 2017 Win64
      ARCH: x64
      BUILD_TYPE: Release
      SHARED: OFF
      make_wheel: false
    - generator: Visual Studio 14 2017
      ARCH: x86
      BUILD_TYPE: Release
      SHARED: ON
      make_wheel: false

clone_depth: 10
clone_folder: c:\lemon

build_script:
  - cmd: >-
      if not %make_wheel% equ true scripts\appveyor\build.bat

test_script:
  - cmd: >-
      if not %make_wheel% equ true ctest --build-config %BUILD_TYPE% --timeout 300 --output-on-failure build

install:
  - ps: >-
      if ($env:make_wheel -eq 'true')
      {
        cd c:\lemon
        .\scripts\appveyor\build-wheels.ps1
      }
