version: "{build}"
os: Visual Studio 2017

branches:
  only:
    - master

environment:
  TWINE_USERNAME:
    secure: QHW0ZSR1Ljzd+51LcuQkvw==
  TWINE_PASSWORD:
    secure: +5HolvKfBONAJAt964XKfg==
  matrix:
    - generator: Visual Studio 15 2017 Win64
      ARCH: x64
      make_wheel: true
    - generator: Visual Studio 15 2017
      ARCH: x86
      SHARED: ON
      make_wheel: false

clone_depth: 10
clone_folder: c:\lemon

build_script:
  - ps: >-
      if ($env:make_wheel -ne 'true')
      {
        New-Item dist -ItemType Directory

        cd c:\lemon
        New-Item build -ItemType Directory
        cd build

        if ($env:ARCH -eq 'x64')
        {
          Set-Item -Path Env:Path -Value ("C:/Python35-x64/;" + $Env:Path)
        } else {
          Set-Item -Path Env:Path -Value ("C:/Python35/;" + $Env:Path)
        }

        cmake .. -DLEMON_TEST_ASYNC=ON `
                 -DBUILD_SHARED_LIBS="$env:SHARED" `
                 -DLEMON_BUILD_PYTHON=ON `
                 -Wno-dev `
                 -G $env:generator

        cmake --build . --config Release -- /v:m /m:2
      }

test_script:
  - ps: >-
      if ($env:make_wheel -ne 'true')
      {
        cd c:\lemon\build
        ctest --build-config Release --timeout 300 --output-on-failure
      } 

install:
  - ps: >-
      if ($env:make_wheel -eq 'true')
      {
        cd c:\lemon
        .\scripts\appveyor\build-wheels.ps1
      }

artifacts:
  - path: dist

deploy_script:
  - ps: >-
      if ($env:appveyor_repo_tag -eq 'true' -and $env:make_wheel -eq 'true')
      {
        cd c:\lemon
        .\scripts\appveyor\upload-pypi.ps1
      }
