version: 2
jobs:
  package:
    working_directory: ~/
    machine: true
    steps:
      - checkout:
          path: ~/lemon
      - run:
          name: Build Python packages
          no_output_timeout: 1.0h
          command: |
            ./lemon/scripts/circleci/dockcross-manylinux-build-wheels.sh cp27 cp34 cp35 cp36 cp37
      - store_artifacts:
          path: dist
          destination: dist
      - run:
          name: Upload to PyPi
          command: |
            ./lemon/scripts/upload_pypi.sh

workflows:
    version: 2
    package_wheel:
      jobs:
        - package:
            filters:
              tags:
                only: /.*/
        - upload:
            requires:
              - package
            filters:
              tags:
                only: /.*/
              branches:
                ignore: /.*/
